### ISSUE TITLE
RWD

### ISSUE THREAD

**Issue by poga** [g0v/summit-assets#1]

**Comment by Rplus** [comment]
小畫面，左側欄的選單要怎麼擺？

**Comment by poga** [comment]
![2016-06-28 10 57 08](https://cloud.githubusercontent.com/assets/8631/16402444/1d653e96-3d1f-11e6-92c3-2f90b8c7c3ac.png)

據說是想要長這樣 XD

**Comment by Rplus** [comment]
這樣子擺，感覺一進網站會不曉得這是什麼網站 (？

**Comment by poga** [comment]
如果在小畫面的上方把那個 2016 summit g0v 的 logo 放回去呢？

**Comment by Rplus** [comment]
也可以試試
不過感覺識別應該是另外的 issue 了 XDD

**Comment by poga** [comment]
已回報設計師 XD

**Comment by poga** [comment]
PR merged. great job!
